name: percival
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bottleneck=1.3.7=py310ha9d4c09_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.7.2=h06a4308_0
  - et_xmlfile=1.1.0=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.8=py310h5eee18b_0
  - mkl_random=1.2.4=py310hdb19cb5_0
  - ncurses=6.4=h6a678d5_0
  - numexpr=2.8.7=py310h85018f9_0
  - numpy-base=1.26.4=py310hb5e798b_0
  - openpyxl=3.1.5=py310h5eee18b_0
  - openssl=3.0.14=h5eee18b_0
  - pandas=2.2.2=py310h6a678d5_0
  - pip=24.0=py310h06a4308_0
  - python=3.10.14=h955ad1f_1
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2024.1=py310h06a4308_0
  - readline=8.2=h5eee18b_0
  - setuptools=72.1.0=py310h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - tzdata=2024a=h04d1e81_0
  - wheel=0.43.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - accelerate==1.3.0
      - annotated-types==0.7.0
      - beartype==0.20.2
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - click==8.1.8
      - contourpy==1.2.1
      - cycler==0.12.1
      - deepspeed==0.16.3
      - einops==0.8.0
      - einx==0.3.0
      - filelock==3.13.1
      - fonttools==4.53.1
      - frozendict==2.4.6
      - fsspec==2024.2.0
      - hjson==3.1.0
      - huggingface-hub==0.24.5
      - idna==3.7
      - imageio==2.34.2
      - jinja2==3.1.3
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - markupsafe==2.1.5
      - matplotlib==3.9.1.post1
      - monai==1.4.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - networkx==3.2.1
      - nibabel==5.2.1
      - ninja==1.11.1.3
      - nltk==3.9.1
      - numpy==1.26.3
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-ml-py==12.560.30
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nvtx-cu11==11.8.86
      - opencv-python==4.10.0.84
      - packaging==24.1
      - pillow==10.2.0
      - protobuf==5.29.3
      - psutil==6.1.1
      - py-cpuinfo==9.0.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyparsing==3.1.2
      - pyyaml==6.0.2
      - regex==2024.7.24
      - requests==2.32.3
      - safetensors==0.4.4
      - scikit-image==0.24.0
      - scipy==1.14.0
      - sentencepiece==0.2.0
      - simpleitk==2.3.1
      - sympy==1.12
      - tifffile==2024.7.24
      - timm==1.0.12
      - tokenizers==0.21.0
      - torch==2.4.0+cu118
      - torchaudio==2.4.0+cu118
      - torchvision==0.19.0+cu118
      - tqdm==4.66.5
      - transformers==4.48.1
      - triton==3.0.0
      - typing-extensions==4.12.2
      - urllib3==2.2.2
      - vector-quantize-pytorch==1.22.10
prefix: /cbica/home/beechec/miniconda3/envs/foundation
